client_id: 3MVG9Y6d_Btp4xp4PfqDtz9JKu6aZ0FxA.2BxWMrtia.2qu84allArDRkO83wtV4UzRuC91Y8aCRp_RcfE7yc
client_secret: 2344389753498573498745
username: user@example.com
password: secret
security_token: Jdkra7ZddJcYEmOaJPvPqBJRW
objects: [Contact, Account]